# -*- coding: utf-8 -*-
"""Copy of CTC_forcealign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f81oqQxxI-e2dAyeYFQsbZA-xZJ189EH
"""

from google.colab import drive
drive.mount('/content/drive')

import os

# 改成你的实际路径
project_root = "/content/drive/MyDrive/Sample Audio_CTC"
processed_dir = f"{project_root}/processed_audio"
transcript_dir = f"{project_root}/transcripts"
alignment_dir  = f"{project_root}/alignments"

os.makedirs(alignment_dir, exist_ok=True)

# 验证
print("processed_audio文件数：", len([f for f in os.listdir(processed_dir) if f.endswith(".wav")]))
print("transcripts文件数：", len([f for f in os.listdir(transcript_dir) if f.endswith(".txt")]))

!pip install ctc-forced-aligner onnxruntime -q

import librosa
import os

for f in sorted(os.listdir(processed_dir)):
    if f.endswith(".wav"):
        duration = librosa.get_duration(path=os.path.join(processed_dir, f))
        print(f"{f}: {duration:.1f}秒")

import onnxruntime as ort
from ctc_forced_aligner import ensure_onnx_model, MODEL_URL

model_path = "/content/ctc_model.onnx"
ensure_onnx_model(model_path, MODEL_URL)

session_options = ort.SessionOptions()
session_options.intra_op_num_threads = 1
session_options.inter_op_num_threads = 1
session = ort.InferenceSession(model_path, sess_options=session_options)
print("模型加载完成")

!pip install pypinyin

import json
import numpy as np
import gc
import re
from pypinyin import lazy_pinyin, Style
from ctc_forced_aligner import (
    load_audio,
    generate_emissions,
    get_alignments,
    get_spans,
    Tokenizer,
    VOCAB_DICT
)

tokenizer = Tokenizer()

def text_to_token_list(text):
    # 先去掉所有标点和非汉字字符
    text_clean = re.sub(r'[^\u4e00-\u9fff]', '', text)
    pinyin = lazy_pinyin(text_clean, style=Style.TONE3)
    pinyin_clean = re.sub(r'[0-9]', '', " ".join(pinyin)).replace(" ", "")
    return list(pinyin_clean)

all_files = sorted([f for f in os.listdir(processed_dir) if f.endswith(".wav")])
print(f"总文件数：{len(all_files)}")

success = 0
failed = []

for i, audio_filename in enumerate(all_files):
    txt_filename = audio_filename.replace(".wav", ".txt")
    txt_path = os.path.join(transcript_dir, txt_filename)
    json_path = os.path.join(alignment_dir, audio_filename.replace(".wav", ".json"))

    if os.path.exists(json_path):
        success += 1
        print(f"[{i+1}/{len(all_files)}] 跳过（已完成）：{audio_filename}")
        continue

    if not os.path.exists(txt_path):
        failed.append(f"缺少转录：{audio_filename}")
        print(f"[{i+1}/{len(all_files)}] ✗ 缺少转录：{audio_filename}")
        continue

    with open(txt_path, "r", encoding="utf-8") as f:
        text = f.read().strip()

    if not text:
        failed.append(f"转录为空：{audio_filename}")
        continue

    try:
        audio = load_audio(os.path.join(processed_dir, audio_filename), 16000)
        audio = np.array(audio).squeeze()
        if audio.ndim != 1:
            audio = audio.mean(axis=0)

        emissions, stride = generate_emissions(session, audio)
        tokens = text_to_token_list(text)
        segments, scores, blank_token = get_alignments(emissions, tokens, tokenizer)
        spans = get_spans(tokens, segments, blank_token)

        # 每个span是一组Segment，取第一个非blank的start和最后一个的end
        results = []
        for span_group, token in zip(spans, tokens):
            # 找非blank的segment
            non_blank = [s for s in span_group if s.label != blank_token]
            if non_blank:
                start_frame = non_blank[0].start
                end_frame = non_blank[-1].end
            else:
                start_frame = span_group[0].start
                end_frame = span_group[-1].end

            start_sec = round(start_frame * stride, 4)
            end_sec = round(end_frame * stride, 4)

            # 平均置信度
            all_frames = range(start_frame, max(end_frame, start_frame + 1))
            score = float(scores[start_frame:end_frame].mean()) if end_frame > start_frame else 0.0

            results.append({
                "text": token,
                "start": start_sec,
                "end": end_sec,
                "score": score
            })

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(results, f, ensure_ascii=False, indent=2)

        success += 1
        print(f"[{i+1}/{len(all_files)}] ✓ {audio_filename}")

    except Exception as e:
        failed.append(f"{audio_filename}: {str(e)}")
        print(f"[{i+1}/{len(all_files)}] ✗ {audio_filename}: {e}")

    finally:
        try:
            del audio, emissions, tokens, segments, spans, results
        except:
            pass
        gc.collect()

print(f"\n完成：{success} 个成功，{len(failed)} 个失败")
for item in failed:
    print(f"  {item}")

failed_files = [
    "1000001_5c8b5985.wav",
    "1000001_63740949.wav",
    "1000001_8d1c9983.wav"
]

for f in failed_files:
    txt_path = os.path.join(transcript_dir, f.replace(".wav", ".txt"))
    with open(txt_path, "r", encoding="utf-8") as fp:
        text = fp.read().strip()
    print(f"{f}:\n  原文：{text}")

    from pypinyin import lazy_pinyin, Style
    import re
    pinyin = lazy_pinyin(text, style=Style.TONE3)
    pinyin_clean = re.sub(r'[0-9]', '', " ".join(pinyin)).replace(" ", "")
    print(f"  拼音：{pinyin_clean}\n")

for audio_filename in failed_files:
    txt_path = os.path.join(transcript_dir, audio_filename.replace(".wav", ".txt"))
    json_path = os.path.join(alignment_dir, audio_filename.replace(".wav", ".json"))

    def text_to_token_list(text):
    # 先去掉所有标点和非汉字字符
      text_clean = re.sub(r'[^\u4e00-\u9fff]', '', text)
      pinyin = lazy_pinyin(text_clean, style=Style.TONE3)
      pinyin_clean = re.sub(r'[0-9]', '', " ".join(pinyin)).replace(" ", "")
      return list(pinyin_clean)

    with open(txt_path, "r", encoding="utf-8") as f:
        text = f.read().strip()

    try:
        audio = load_audio(os.path.join(processed_dir, audio_filename), 16000)
        audio = np.array(audio).squeeze()
        if audio.ndim != 1:
            audio = audio.mean(axis=0)

        emissions, stride = generate_emissions(session, audio)
        tokens = text_to_token_list(text)
        segments, scores, blank_token = get_alignments(emissions, tokens, tokenizer)
        spans = get_spans(tokens, segments, blank_token)

        results = []
        for span_group, token in zip(spans, tokens):
            non_blank = [s for s in span_group if s.label != blank_token]
            if non_blank:
                start_frame = non_blank[0].start
                end_frame = non_blank[-1].end
            else:
                start_frame = span_group[0].start
                end_frame = span_group[-1].end

            start_sec = round(start_frame * stride, 4)
            end_sec = round(end_frame * stride, 4)
            score = float(scores[start_frame:end_frame].mean()) if end_frame > start_frame else 0.0

            results.append({
                "text": token,
                "start": start_sec,
                "end": end_sec,
                "score": score
            })

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(results, f, ensure_ascii=False, indent=2)

        print(f"✓ {audio_filename}")

    except Exception as e:
        print(f"✗ {audio_filename}: {e}")

    finally:
        try:
            del audio, emissions, tokens, segments, spans, results
        except:
            pass
        gc.collect()

import librosa
import json
import os

textgrid_dir = f"{project_root}/textgrids"
os.makedirs(textgrid_dir, exist_ok=True)

def json_to_textgrid(json_path, audio_duration, output_path):
    with open(json_path, "r", encoding="utf-8") as f:
        segments = json.load(f)
    n = len(segments)
    lines = [
        'File type = "ooTextFile"',
        'Object class = "TextGrid"',
        '',
        'xmin = 0',
        f'xmax = {audio_duration}',
        'tiers? <exists>',
        'size = 1',
        'item []:',
        '    item [1]:',
        '        class = "IntervalTier"',
        '        name = "syllable"',
        '        xmin = 0',
        f'        xmax = {audio_duration}',
        f'        intervals: size = {n}',
    ]
    for i, seg in enumerate(segments, 1):
        lines += [
            f'        intervals [{i}]:',
            f'            xmin = {seg["start"]}',
            f'            xmax = {seg["end"]}',
            f'            text = "{seg["text"]}"',
        ]
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

converted = 0
for json_filename in sorted(os.listdir(alignment_dir)):
    if not json_filename.endswith(".json"):
        continue
    wav_path = os.path.join(processed_dir, json_filename.replace(".json", ".wav"))
    if not os.path.exists(wav_path):
        print(f"找不到对应音频：{json_filename}")
        continue
    duration = librosa.get_duration(path=wav_path)
    tg_path = os.path.join(textgrid_dir, json_filename.replace(".json", ".TextGrid"))
    json_to_textgrid(os.path.join(alignment_dir, json_filename), duration, tg_path)
    converted += 1

print(f"TextGrid转换完成：{converted} 个文件")

import numpy as np

issues = []
all_durations = []
all_scores = []

for filename in sorted(os.listdir(alignment_dir)):
    if not filename.endswith(".json"):
        continue
    with open(os.path.join(alignment_dir, filename)) as f:
        segments = json.load(f)

    for seg in segments:
        duration = seg["end"] - seg["start"]
        score = seg.get("score", 1.0)
        all_durations.append(duration)
        all_scores.append(score)

        if duration < 0.02:
            issues.append(f"{filename} | '{seg['text']}' | 时长过短 {duration:.3f}s")
        elif duration > 0.6:
            issues.append(f"{filename} | '{seg['text']}' | 时长过长 {duration:.3f}s")
        if score < 0.3:
            issues.append(f"{filename} | '{seg['text']}' | 置信度低 {score:.3f}")

print("=== 整体统计 ===")
print(f"总音素数：{len(all_durations)}")
print(f"平均时长：{np.mean(all_durations):.3f}s")
print(f"时长范围：{np.min(all_durations):.3f}s — {np.max(all_durations):.3f}s")
print(f"平均置信度：{np.mean(all_scores):.3f}")
print(f"\n潜在问题：{len(issues)} 个")
for issue in issues[:20]:
    print(f"  {issue}")

# 查看第一个JSON的原始内容
with open(os.path.join(alignment_dir, "1000001_0b1a33a3.json")) as f:
    data = json.load(f)

print(f"总条目数：{len(data)}")
print("\n前10条：")
for item in data[:10]:
    print(item)

# 同时查看对应转录
with open(os.path.join(transcript_dir, "1000001_0b1a33a3.txt")) as f:
    text = f.read().strip()
print(f"\n转录文本：{text}")
print(f"文本长度：{len(text)} 个字符")

# 查看stride值
audio = load_audio(os.path.join(processed_dir, "1000001_0b1a33a3.wav"), 16000)
audio = np.array(audio).squeeze()
emissions, stride = generate_emissions(session, audio)
print(f"\nstride值：{stride}")
print(f"emissions shape：{emissions.shape}")
print(f"音频长度：{len(audio)/16000:.2f}秒")

import json
import numpy as np
import gc
import re
from pypinyin import lazy_pinyin, Style
from ctc_forced_aligner import (
    load_audio,
    generate_emissions,
    get_alignments,
    get_spans,
    Tokenizer,
    VOCAB_DICT
)

tokenizer = Tokenizer()

def text_to_syllable_phonemes(text):
    """返回：[(汉字, [音素列表]), ...]"""
    text_clean = re.sub(r'[^\u4e00-\u9fff]', '', text)
    result = []
    for char in text_clean:
        pinyin = lazy_pinyin(char, style=Style.TONE3)[0]
        phonemes = list(re.sub(r'[0-9]', '', pinyin))
        result.append((char, phonemes))
    return result

all_files = sorted([f for f in os.listdir(processed_dir) if f.endswith(".wav")])
print(f"总文件数：{len(all_files)}")

success = 0
failed = []

for i, audio_filename in enumerate(all_files):
    txt_filename = audio_filename.replace(".wav", ".txt")
    txt_path = os.path.join(transcript_dir, txt_filename)
    json_path = os.path.join(alignment_dir, audio_filename.replace(".wav", ".json"))

    # 删除旧的json重新生成
    if os.path.exists(json_path):
        os.remove(json_path)

    if not os.path.exists(txt_path):
        failed.append(f"缺少转录：{audio_filename}")
        continue

    with open(txt_path, "r", encoding="utf-8") as f:
        text = f.read().strip()

    if not text:
        failed.append(f"转录为空：{audio_filename}")
        continue

    try:
        audio = load_audio(os.path.join(processed_dir, audio_filename), 16000)
        audio = np.array(audio).squeeze()
        if audio.ndim != 1:
            audio = audio.mean(axis=0)

        emissions, stride = generate_emissions(session, audio)

        # 音节→音素映射
        syllable_phonemes = text_to_syllable_phonemes(text)
        all_phonemes = []
        for char, phonemes in syllable_phonemes:
            all_phonemes.extend(phonemes)

        segments, scores, blank_token = get_alignments(
            emissions, all_phonemes, tokenizer
        )
        spans = get_spans(all_phonemes, segments, blank_token)

        # spans是每个音素的span组，按音节合并
        results = []
        phoneme_idx = 0
        for char, phonemes in syllable_phonemes:
            n = len(phonemes)
            char_spans = spans[phoneme_idx: phoneme_idx + n]
            phoneme_idx += n

            # 收集这个汉字所有音素的帧
            all_frames = []
            for span_group in char_spans:
                for seg in span_group:
                    if seg.label != blank_token:
                        all_frames.extend(range(seg.start, max(seg.end, seg.start + 1)))

            if all_frames:
                start_frame = min(all_frames)
                end_frame = max(all_frames)
            else:
                # fallback：用span_group边界
                start_frame = char_spans[0][0].start
                end_frame = char_spans[-1][-1].end

            # stride单位是毫秒，转换成秒
            start_sec = round(start_frame * stride / 1000, 4)
            end_sec = round(end_frame * stride / 1000, 4)

            # 置信度
            if end_frame > start_frame:
                score = float(scores[start_frame:end_frame].mean())
            else:
                score = float(scores[start_frame])

            results.append({
                "text": char,
                "start": start_sec,
                "end": end_sec,
                "score": score
            })

        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(results, f, ensure_ascii=False, indent=2)

        success += 1
        print(f"[{i+1}/{len(all_files)}] ✓ {audio_filename}")

    except Exception as e:
        failed.append(f"{audio_filename}: {str(e)}")
        print(f"[{i+1}/{len(all_files)}] ✗ {audio_filename}: {e}")

    finally:
        try:
            del audio, emissions, all_phonemes, segments, spans, results
        except:
            pass
        gc.collect()

print(f"\n完成：{success} 个成功，{len(failed)} 个失败")
for item in failed:
    print(f"  {item}")

import numpy as np
import json
import os

issues = []
all_durations = []
all_scores = []

for filename in sorted(os.listdir(alignment_dir)):
    if not filename.endswith(".json"):
        continue
    with open(os.path.join(alignment_dir, filename)) as f:
        segments = json.load(f)

    for seg in segments:
        duration = seg["end"] - seg["start"]
        score = seg.get("score", 1.0)
        all_durations.append(duration)
        all_scores.append(score)

        if duration < 0.05:
            issues.append(f"{filename} | '{seg['text']}' | 时长过短 {duration:.3f}s")
        elif duration > 0.8:
            issues.append(f"{filename} | '{seg['text']}' | 时长过长 {duration:.3f}s")
        if score < -0.5:
            issues.append(f"{filename} | '{seg['text']}' | 置信度低 {score:.3f}")

print("=== 整体统计 ===")
print(f"总音节数：{len(all_durations)}")
print(f"平均时长：{np.mean(all_durations):.3f}s")
print(f"时长范围：{np.min(all_durations):.3f}s — {np.max(all_durations):.3f}s")
print(f"平均置信度：{np.mean(all_scores):.3f}")
print(f"\n潜在问题：{len(issues)} 个")
for issue in issues[:20]:
    print(f"  {issue}")

# 打印几个样本确认格式正确
print("\n=== 样本检查（第一个文件前5个音节）===")
first_json = sorted([f for f in os.listdir(alignment_dir) if f.endswith(".json")])[0]
with open(os.path.join(alignment_dir, first_json)) as f:
    sample = json.load(f)
for seg in sample[:5]:
    print(f"  {seg['text']}  {seg['start']:.3f}s — {seg['end']:.3f}s  score:{seg['score']:.3f}")

import librosa
import json
import os

textgrid_dir = f"{project_root}/textgrids"
os.makedirs(textgrid_dir, exist_ok=True)

def json_to_textgrid_no_gap(json_path, audio_duration, output_path):
    with open(json_path, "r", encoding="utf-8") as f:
        segments = json.load(f)

    n = len(segments)

    # 强制对齐边界：前一个字的xmax = 后一个字的xmin
    boundaries = []
    for i, seg in enumerate(segments):
        if i == 0:
            # 第一个字：xmin从0开始
            xmin = 0.0
        else:
            # 每个字的xmin = 上一个字的xmax
            xmin = boundaries[-1][1]

        # xmax用当前字的end，但最后一个字用音频总时长
        if i == n - 1:
            xmax = round(audio_duration, 4)
        else:
            # 当前字的end和下一个字的start取中点，避免overlap
            current_end = seg["end"]
            next_start = segments[i + 1]["start"]
            if current_end <= next_start:
                # 正常情况：取中点
                xmax = round((current_end + next_start) / 2, 4)
            else:
                # overlap情况：直接用当前end
                xmax = round(current_end, 4)

        boundaries.append((xmin, xmax))

    lines = [
        'File type = "ooTextFile"',
        'Object class = "TextGrid"',
        '',
        'xmin = 0',
        f'xmax = {audio_duration}',
        'tiers? <exists>',
        'size = 1',
        'item []:',
        '    item [1]:',
        '        class = "IntervalTier"',
        '        name = "syllable"',
        '        xmin = 0',
        f'        xmax = {audio_duration}',
        f'        intervals: size = {n}',
    ]

    for i, (seg, (xmin, xmax)) in enumerate(zip(segments, boundaries), 1):
        lines += [
            f'        intervals [{i}]:',
            f'            xmin = {xmin}',
            f'            xmax = {xmax}',
            f'            text = "{seg["text"]}"',
        ]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

# 批量转换
converted = 0
for json_filename in sorted(os.listdir(alignment_dir)):
    if not json_filename.endswith(".json"):
        continue
    wav_path = os.path.join(processed_dir, json_filename.replace(".json", ".wav"))
    if not os.path.exists(wav_path):
        print(f"找不到对应音频：{json_filename}")
        continue
    duration = librosa.get_duration(path=wav_path)
    tg_path = os.path.join(textgrid_dir, json_filename.replace(".json", ".TextGrid"))
    json_to_textgrid_no_gap(
        os.path.join(alignment_dir, json_filename),
        duration,
        tg_path
    )
    converted += 1

print(f"TextGrid转换完成：{converted} 个文件")

# 验证：检查所有相邻interval的边界是否对齐
print("验证边界连续性：")
first_tg = sorted([f for f in os.listdir(textgrid_dir) if f.endswith(".TextGrid")])[0]

with open(os.path.join(textgrid_dir, first_tg), "r", encoding="utf-8") as f:
    content = f.read()

# 提取所有xmin和xmax
import re
xmins = [float(x) for x in re.findall(r'xmin = ([\d.]+)', content)[2:]]  # 跳过文件头的两个
xmaxs = [float(x) for x in re.findall(r'xmax = ([\d.]+)', content)[2:]]
texts = re.findall(r'text = "(.+)"', content)

print(f"{'汉字':<6} {'xmin':<10} {'xmax':<10} {'时长':<8} {'间隔'}")
for i in range(len(texts)):
    gap = xmins[i+1] - xmaxs[i] if i < len(texts)-1 else 0
    gap_str = f"{gap:.4f}" if gap != 0 else "✓连续"
    print(f"{texts[i]:<6} {xmins[i]:<10.4f} {xmaxs[i]:<10.4f} {xmaxs[i]-xmins[i]:<8.4f} {gap_str}")