# -*- coding: utf-8 -*-
"""ctcf0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14yQxPGRok7q_rORH1eea-5Ns9u8eooeI
"""

from google.colab import drive
drive.mount('/content/drive')

import os

#实际路径
project_root = "/content/drive/MyDrive/ctcSA (1)"
processed_dir = f"{project_root}/processed_audio"
transcript_dir = f"{project_root}/transcripts"
alignment_dir  = f"{project_root}/alignments"
f0_dir        = f"{project_root}/f0_results"

os.makedirs(f0_dir, exist_ok=True)

#验证文件数
print("processed_audio文件数：", len([f for f in os.listdir(processed_dir) if f.endswith(".wav")]))
print("transcripts文件数：", len([f for f in os.listdir(transcript_dir) if f.endswith(".txt")]))

!pip install librosa numpy scipy -q

import librosa
import numpy as np
import json
import os
from scipy.interpolate import interp1d
from scipy.fftpack import dct

SR = 16000
#时间归一化点数
N_POINTS = 10

def extract_f0_pyin(audio, sr, start_sec, end_sec):
    """从音节时间段提取F0轨迹"""
    start_sample = int(start_sec * sr)
    end_sample   = int(end_sec * sr)
    segment = audio[start_sample:end_sample]

    if len(segment) < 512:
        return None, None

    f0, voiced_flag, voiced_probs = librosa.pyin(
        segment,
        fmin=63,
        fmax=400,
        sr=sr,
        frame_length=640,
        hop_length=128
    )
    return f0, voiced_flag

def hz_to_semitone(f0, speaker_median_f0):
    """Hz转半音（说话人归一化）"""
    with np.errstate(divide='ignore', invalid='ignore'):
        semitones = 12 * np.log2(f0 / speaker_median_f0)
    return semitones

def interpolate_f0(f0, voiced_flag):
    """插值填补清音段"""
    if voiced_flag is None or not np.any(voiced_flag):
        return None

    frames = np.arange(len(f0))
    voiced_frames = frames[voiced_flag]
    voiced_f0 = f0[voiced_flag]

    if len(voiced_frames) < 2:
        return None

    interp_func = interp1d(
        voiced_frames, voiced_f0,
        kind='linear',
        bounds_error=False,
        fill_value=(voiced_f0[0], voiced_f0[-1])
    )
    return interp_func(frames)

def normalize_time(f0_interp, n_points=10):
    """时间归一化到n_points个等距点"""
    if f0_interp is None or len(f0_interp) < 2:
        return None
    x_old = np.linspace(0, 1, len(f0_interp))
    x_new = np.linspace(0, 1, n_points)
    interp_func = interp1d(x_old, f0_interp, kind='linear')
    return interp_func(x_new)

def compute_dct(f0_normalized):
    """计算DCT系数"""
    coeffs = dct(f0_normalized, norm='ortho')
    return coeffs[0], coeffs[1], coeffs[2]  # C0, C1, C2

#main

all_files = sorted([f for f in os.listdir(processed_dir) if f.endswith(".wav")])
print(f"处理文件数：{len(all_files)}")

all_results = []

for audio_filename in all_files:
    json_filename = audio_filename.replace(".wav", ".json")
    json_path = os.path.join(alignment_dir, json_filename)

    if not os.path.exists(json_path):
        print(f"✗ 缺少alignment：{audio_filename}")
        continue

    #读取音频
    audio, sr = librosa.load(
        os.path.join(processed_dir, audio_filename),
        sr=SR, mono=True
    )

    #读取音节边界
    with open(json_path, "r", encoding="utf-8") as f:
        segments = json.load(f)

    #计算说话人F0中位数（用于归一化）
    all_f0_values = []
    for seg in segments:
        f0, voiced_flag = extract_f0_pyin(audio, SR, seg["start"], seg["end"])
        if f0 is not None and voiced_flag is not None:
            voiced_f0 = f0[voiced_flag & ~np.isnan(f0)]
            all_f0_values.extend(voiced_f0.tolist())

    if not all_f0_values:
        print(f"✗ 无有效F0：{audio_filename}")
        continue

    speaker_median = np.median(all_f0_values)

    #逐音节提取F0特征
    file_results = []
    for seg in segments:
        char = seg["text"]
        start = seg["start"]
        end   = seg["end"]
        duration_ms = round((end - start) * 1000, 1)

        f0, voiced_flag = extract_f0_pyin(audio, SR, start, end)

        if f0 is None or voiced_flag is None or not np.any(voiced_flag):
            file_results.append({
                "file": audio_filename,
                "char": char,
                "start": start,
                "end": end,
                "duration_ms": duration_ms,
                "speaker_median_hz": round(speaker_median, 2),
                "f0_10pts_semitone": None,
                "C0": None, "C1": None, "C2": None,
                "voiced_ratio": 0.0,
                "error": "no_voiced_frames"
            })
            continue

        #插值
        f0_interp = interpolate_f0(f0, voiced_flag)
        if f0_interp is None:
            file_results.append({
                "file": audio_filename,
                "char": char,
                "start": start,
                "end": end,
                "duration_ms": duration_ms,
                "speaker_median_hz": round(speaker_median, 2),
                "f0_10pts_semitone": None,
                "C0": None, "C1": None, "C2": None,
                "voiced_ratio": 0.0,
                "error": "interp_failed"
            })
            continue

        #说话人归一化
        f0_semitone = hz_to_semitone(f0_interp, speaker_median)

        #时间归一化到10个点
        f0_normalized = normalize_time(f0_semitone, N_POINTS)
        if f0_normalized is None:
            continue

        #DCT系数
        C0, C1, C2 = compute_dct(f0_normalized)

        #voiced比例
        voiced_ratio = float(np.sum(voiced_flag) / len(voiced_flag))

        file_results.append({
            "file": audio_filename,
            "char": char,
            "start": start,
            "end": end,
            "duration_ms": duration_ms,
            "speaker_median_hz": round(speaker_median, 2),
            "f0_10pts_semitone": [round(x, 4) for x in f0_normalized.tolist()],
            "C0": round(float(C0), 4),
            "C1": round(float(C1), 4),
            "C2": round(float(C2), 4),
            "voiced_ratio": round(voiced_ratio, 3),
            "error": None
        })

    #保存每个文件的结果
    out_path = os.path.join(f0_dir, audio_filename.replace(".wav", "_f0.json"))
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(file_results, f, ensure_ascii=False, indent=2)

    all_results.extend(file_results)
    print(f"✓ {audio_filename}  ({len(file_results)}个音节，说话人中位F0={speaker_median:.1f}Hz)")

print(f"\n完成：{len(all_results)} 个音节总计")

import csv

csv_path = os.path.join(project_root, "f0_all.csv")

fieldnames = [
    "file", "char", "start", "end", "duration_ms",
    "speaker_median_hz",
    "f0_t1","f0_t2","f0_t3","f0_t4","f0_t5",
    "f0_t6","f0_t7","f0_t8","f0_t9","f0_t10",
    "C0","C1","C2",
    "voiced_ratio", "error"
]

with open(csv_path, "w", newline="", encoding="utf-8") as csvfile:
    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()

    for row in all_results:
        flat = {k: v for k, v in row.items() if k != "f0_10pts_semitone"}
        pts = row.get("f0_10pts_semitone") or [None]*10
        for j, pt in enumerate(pts, 1):
            flat[f"f0_t{j}"] = pt
        writer.writerow(flat)

print(f"CSV保存完成：{csv_path}")
print(f"总行数：{len(all_results)}")

import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family'] = 'DejaVu Sans'

#取前6个有效音节画图
valid = [r for r in all_results if r["f0_10pts_semitone"] is not None][:6]

fig, axes = plt.subplots(2, 3, figsize=(12, 6))
axes = axes.flatten()

for i, row in enumerate(valid):
    pts = row["f0_10pts_semitone"]
    axes[i].plot(range(1, 11), pts, 'o-', color='steelblue')
    axes[i].set_title(f"{row['char']}  ({row['duration_ms']}ms)", fontsize=12)
    axes[i].set_xlabel("Time point")
    axes[i].set_ylabel("Semitone")
    axes[i].set_xticks(range(1, 11))
    axes[i].grid(True, alpha=0.3)
    axes[i].set_ylim(-6, 6)

plt.tight_layout()
plt.savefig(os.path.join(project_root, "f0_sample.png"), dpi=150)
plt.show()
print("图片已保存")

!pip install pypinyin -q

from pypinyin import lazy_pinyin, Style
import pandas as pd
import re

df = pd.read_csv(f"{project_root}/f0_all.csv")

def get_tone(char):
    """获取汉字声调数字 1/2/3/4，轻声返回0"""
    if not char or not re.match(r'[\u4e00-\u9fff]', char):
        return None
    result = lazy_pinyin(char, style=Style.TONE3)
    if not result:
        return None
    pinyin = result[0]
    #提取最后一个数字
    match = re.search(r'[1-4]$', pinyin)
    if match:
        return int(match.group())
    return 0  #轻声

df['tone'] = df['char'].apply(get_tone)

#查看声调分布
print("声调分布：")
print(df['tone'].value_counts().sort_index())
print(f"\n总音节数：{len(df)}")
print(f"有声调标注：{df['tone'].notna().sum()}")

#保存带声调的CSV
output_path = f"{project_root}/f0_with_tone.csv"
df.to_csv(output_path, index=False, encoding='utf-8')
print(f"\n已保存：{output_path}")

import pandas as pd
import numpy as np

df = pd.read_csv(f"{project_root}/f0_with_tone.csv")

print(f"清洗前：{len(df)} 行")

#过滤条件
mask = (
    df['C0'].notna() &
    (df['voiced_ratio'] > 0.3) &
    df['C0'].between(-10, 15) &
    df['C1'].between(-10, 10) &
    df['tone'].notna() &
    (df['tone'] != 0)
)

df_clean = df[mask].copy()
print(f"清洗后：{len(df_clean)} 行")

print("\n清洗后声调分布：")
print(df_clean['tone'].value_counts().sort_index())

print("\n各声调DCT系数均值：")
print(df_clean.groupby('tone')[['C0','C1','C2','duration_ms']].mean().round(3))

#保存
df_clean.to_csv(f"{project_root}/f0_clean.csv", index=False, encoding='utf-8')
print(f"\n已保存：f0_clean.csv")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv(f"{project_root}/f0_clean.csv")

tone_labels = {1: 'T1 阴平', 2: 'T2 阳平', 3: 'T3 上声', 4: 'T4 去声'}
colors = {1: 'steelblue', 2: 'coral', 3: 'green', 4: 'purple'}

f0_cols = [f'f0_t{i}' for i in range(1, 11)]

fig, axes = plt.subplots(1, 4, figsize=(16, 4))

for idx, tone in enumerate([1, 2, 3, 4]):
    ax = axes[idx]
    subset = df[df['tone'] == tone]

    #画每条曲线（淡色）
    for _, row in subset.iterrows():
        vals = row[f0_cols].values.astype(float)
        ax.plot(range(1, 11), vals, color=colors[tone], alpha=0.15, linewidth=0.8)

    #画均值曲线（深色加粗）
    mean_vals = subset[f0_cols].mean().values
    ax.plot(range(1, 11), mean_vals, color=colors[tone],
            linewidth=2.5, label=f'n={len(subset)}')

    ax.set_title(f'{tone_labels[tone]}', fontsize=13)
    ax.set_xlabel('Time point')
    ax.set_ylabel('Semitone')
    ax.set_xticks(range(1, 11))
    ax.set_ylim(-8, 10)
    ax.axhline(0, color='gray', linewidth=0.5, linestyle='--')
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)

plt.suptitle('F0 contours by tone (speaker-normalized, semitone)',
             fontsize=14, y=1.02)
plt.tight_layout()
plt.savefig(f"{project_root}/f0_by_tone.png", dpi=150, bbox_inches='tight')
plt.show()
print("图片已保存")

import numpy as np
import pandas as pd
import librosa
import os

df = pd.read_csv(f"{project_root}/f0_clean.csv")

def extract_hnr(audio, sr, start_sec, end_sec):
    """
    用自相关法估计HNR
    HNR(dB) = 10 * log10(R_peak / (1 - R_peak))
    R_peak = 基频处的归一化自相关峰值
    """
    start_sample = int(start_sec * sr)
    end_sample   = int(end_sec * sr)
    segment = audio[start_sample:end_sample]

    if len(segment) < 512:
        return None

    #加窗
    if len(segment) < 2048:
        segment = np.pad(segment, (0, 2048 - len(segment)))

    #归一化自相关
    autocorr = np.correlate(segment, segment, mode='full')
    autocorr = autocorr[len(autocorr)//2:]  #只取正延迟部分
    autocorr = autocorr / (autocorr[0] + 1e-10)  #归一化

    #在基频对应的lag范围内找峰值
    #50Hz → lag=320, 400Hz → lag=40 (at sr=16000)
    min_lag = int(sr / 400)
    max_lag = int(sr / 50)
    max_lag = min(max_lag, len(autocorr) - 1)

    if min_lag >= max_lag:
        return None

    peak = np.max(autocorr[min_lag:max_lag])
    peak = np.clip(peak, 0, 0.9999)

    #转换为dB
    hnr_db = 10 * np.log10(peak / (1 - peak + 1e-10))
    return round(float(hnr_db), 3)

#按文件分组处理
print("提取HNR...")
hnr_values = []

#预加载所有音频文件
audio_cache = {}

for idx, row in df.iterrows():
    filename = row['file']

    #缓存音频，避免重复读取
    if filename not in audio_cache:
        audio_path = os.path.join(processed_dir, filename)
        audio, sr = librosa.load(audio_path, sr=16000, mono=True)
        audio_cache[filename] = (audio, sr)

    audio, sr = audio_cache[filename]
    hnr = extract_hnr(audio, sr, row['start'], row['end'])
    hnr_values.append(hnr)

df['HNR'] = hnr_values

#统计
print(f"HNR提取完成")
print(f"有效HNR：{df['HNR'].notna().sum()} 个")
print(f"无效HNR：{df['HNR'].isna().sum()} 个")
print(f"\nHNR统计：")
print(df['HNR'].describe().round(2))

print(f"\n各声调HNR均值：")
print(df.groupby('tone')['HNR'].mean().round(2))

#保存
df.to_csv(f"{project_root}/f0_clean.csv", index=False, encoding='utf-8')
print(f"\n已更新：f0_clean.csv（新增HNR列）")