# -*- coding: utf-8 -*-
"""ctcstats.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iP4ny_LsQeFcDCda_gn72SgQcpwBTpVc
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np

project_root = "/content/drive/MyDrive/ctcSA (1)"
df = pd.read_csv(f"{project_root}/f0_clean.csv")

print(f"总样本数：{len(df)}")
print(f"声调分布：\n{df['tone'].value_counts().sort_index()}")
print(f"\n列名：{df.columns.tolist()}")

!pip install statsmodels pingouin -q

import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family'] = 'DejaVu Sans'

tone_labels = {1:'T1', 2:'T2', 3:'T3', 4:'T4'}

#各声调特征均值表
summary = df.groupby('tone').agg(
    n=('C0','count'),
    C0_mean=('C0','mean'),
    C0_std=('C0','std'),
    C1_mean=('C1','mean'),
    C1_std=('C1','std'),
    C2_mean=('C2','mean'),
    C2_std=('C2','std'),
    duration_mean=('duration_ms','mean'),
    HNR_mean=('HNR','mean')
).round(3)

print("各声调描述性统计：")
print(summary.to_string())

from scipy import stats

print("单因素ANOVA：各声调的DCT系数是否有显著差异\n")

for feature in ['C0', 'C1', 'C2', 'duration_ms', 'HNR']:
    groups = [df[df['tone']==t][feature].dropna().values for t in [1,2,3,4]]

    F, p = stats.f_oneway(*groups)
    sig = "***" if p < 0.001 else "**" if p < 0.01 else "*" if p < 0.05 else "ns"
    print(f"{feature:<15} F={F:.3f}  p={p:.4f}  {sig}")

print("\n*** p<0.001  ** p<0.01  * p<0.05  ns=不显著")

from statsmodels.stats.multicomp import pairwise_tukeyhsd

print("Tukey HSD 两两比较\n")

for feature in ['C0', 'C1', 'C2', 'HNR']:
    print(f"── {feature} ──")
    subset = df[['tone', feature]].dropna()
    result = pairwise_tukeyhsd(
        endog=subset[feature],
        groups=subset['tone'],
        alpha=0.05
    )
    #打印显著的对比
    summary_df = pd.DataFrame(
        data=result._results_table.data[1:],
        columns=result._results_table.data[0]
    )
    sig_pairs = summary_df[summary_df['reject'] == True]
    if len(sig_pairs) > 0:
        print(sig_pairs[['group1','group2','meandiff','p-adj']].to_string(index=False))
    else:
        print("无显著差异对")
    print()

import statsmodels.formula.api as smf

print("混合效应模型")
print("目的：控制文件（utterance）级别的随机效应后，声调对各特征的影响\n")

# 把tone转成categorical
df['tone_cat'] = df['tone'].astype(str)

for feature in ['C0', 'C1', 'C2']:
    try:
        model = smf.mixedlm(
            f"{feature} ~ tone_cat",
            data=df.dropna(subset=[feature, 'tone_cat', 'file']),
            groups=df.dropna(subset=[feature, 'tone_cat', 'file'])['file']
        )
        result = model.fit(reml=True, method='lbfgs')
        print(f"── {feature} ~ tone（随机效应：file）──")
        print(f"  T1（基准）vs T2: coef={result.params.get('tone_cat[T.2]',0):.3f}, p={result.pvalues.get('tone_cat[T.2]',1):.4f}")
        print(f"  T1（基准）vs T3: coef={result.params.get('tone_cat[T.3]',0):.3f}, p={result.pvalues.get('tone_cat[T.3]',1):.4f}")
        print(f"  T1（基准）vs T4: coef={result.params.get('tone_cat[T.4]',0):.3f}, p={result.pvalues.get('tone_cat[T.4]',1):.4f}")
        print()
    except Exception as e:
        print(f"  {feature} 模型失败：{e}\n")

fig, axes = plt.subplots(1, 3, figsize=(14, 5))

for idx, feature in enumerate(['C0', 'C1', 'C2']):
    ax = axes[idx]
    data_by_tone = [df[df['tone']==t][feature].dropna().values for t in [1,2,3,4]]

    bp = ax.boxplot(data_by_tone,
                    labels=['T1','T2','T3','T4'],
                    patch_artist=True,
                    medianprops=dict(color='black', linewidth=2))

    colors = ['steelblue','coral','green','purple']
    for patch, color in zip(bp['boxes'], colors):
        patch.set_facecolor(color)
        patch.set_alpha(0.7)

    ax.set_title(f'{feature} by tone', fontsize=13)
    ax.set_xlabel('Tone')
    ax.set_ylabel(feature)
    ax.axhline(0, color='gray', linewidth=0.5, linestyle='--')
    ax.grid(True, alpha=0.3)

plt.suptitle('DCT coefficients by tone', fontsize=14)
plt.tight_layout()
plt.savefig(f"{project_root}/stats_boxplot.png", dpi=150)
plt.show()
print("图片已保存")

f0_cols = [f'f0_t{i}' for i in range(1, 11)]
colors = {1:'steelblue', 2:'coral', 3:'green', 4:'purple'}
tone_labels = {1:'T1 (n=58)', 2:'T2 (n=36)', 3:'T3 (n=33)', 4:'T4 (n=91)'}

fig, ax = plt.subplots(figsize=(10, 6))

for tone in [1, 2, 3, 4]:
    subset = df[df['tone']==tone][f0_cols].values
    mean = np.mean(subset, axis=0)
    se = np.std(subset, axis=0) / np.sqrt(len(subset))
    x = range(1, 11)

    ax.plot(x, mean, color=colors[tone], linewidth=2.5,
            label=tone_labels[tone])
    ax.fill_between(x, mean-se, mean+se,
                    color=colors[tone], alpha=0.15)

ax.axhline(0, color='gray', linewidth=0.5, linestyle='--')
ax.set_xlabel('Time point', fontsize=12)
ax.set_ylabel('Semitone (speaker-normalized)', fontsize=12)
ax.set_title('Mean F0 contours by tone (±1 SE)', fontsize=13)
ax.set_xticks(range(1, 11))
ax.legend(fontsize=11)
ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(f"{project_root}/stats_f0_mean.png", dpi=150)
plt.show()
print("图片已保存")